### ISSUE TITLE
RFE: Highlight current line

### ISSUE THREAD

**Issue by gbraad** [deathau/cm-typewriter-scroll-obsidian#44]
Instead of darkening the rest of the text, is it possible to use a background color for the line? Perhaps even scale the line a little to increase visibility even more?

**Comment by gbraad** [comment]
This is what I used for my Zettlr theme:

```css
body.dark #editor .CodeMirror .CodeMirror-linebackground.typewriter-active-line,
body.dark .quicklook .body .CodeMirror .CodeMirror-linebackground.typewriter-active-line,
body.dark .dialog .CodeMirror .CodeMirror-linebackground.typewriter-active-line {
    background-color: #2a2a2a;
}
```

Is something similar availabel?

**Comment by gbraad** [comment]
The following works for me
```scss
body.plugin-cm-typewriter-scroll-zen .CodeMirror-lines.selecting .CodeMirror-code > .CodeMirror-activeline {
  background-color: #333333;
}
                                                                                                                 
body.plugin-cm-typewriter-scroll-zen .cm-editor.cm-focused .cm-line.cm-active {                                   
  background-color: #333333;
}
```

![Screenshot from 2023-02-19 15-33-18](https://user-images.githubusercontent.com/1894/219935162-c6ed9a98-6afd-486e-8fdd-59654a805138.png)

Besides the color I also played around with padding and scaling which gives some nice results.

```css
  transform: scale(1.05);
  padding-top: 8px;
  padding-bottom: 8px;
```

![Screenshot from 2023-02-19 15-28-57](https://user-images.githubusercontent.com/1894/219935081-e39946be-dd84-4794-a712-2ccfba302449.png)

Options for this would be nice to have. WDYT?
