### ISSUE TITLE
Conflict with Obsidian's new Table View

### ISSUE THREAD

**Issue by acook** [deathau/cm-typewriter-scroll-obsidian#50]
Causes tables to expand wildly in every direction and makes them unusable in the pre-release versions, and probably will continue to when it becomes official.

It does seem like development has discontinued but this plugin has been enabled pretty much from day 1 that I started using Obsidian. So either way, thanks for almost a year of making my Obsidian experience better!

**Comment by ces3001** [comment]
I can confirm this bug in Obsidian v1.5.3 macOS. 
Hopefully somebody can look into it if developer isn’t maintaining! I agree it’s a game-changer plug-in! Thank you deathau!

**Comment by acook** [comment]
There's another plugin called "Typewriter Mode" and it doesn't destroy tables, but it does jump around weirdly in tables. So it doesn't really solve the problem either, but it's worth trying out if you just do some minor table editing.

**Comment by mouawadma** [comment]
Also confirm that this plugin is an issue with the new tables in Obsidian

**Comment by rorar** [comment]
Here's a quick fix:

```css
table td .cm-content.cm-lineWrapping {
    padding-top: 0px !important;
    padding-bottom: 0px !important;
}
```

Create a file called `tw-table-fix.css` and add add it to the folder "\.obsidian\snippets" inside your vault and activate the script under Settings > Appearance (scroll to the bottom of the settings page to do so)

**Comment by ursa-minor-13** [comment]
Thanks for the quick fix!

For me it fixed only the table body (Obsidian v1.5.10).
In order to make it work in the header, you may also match the `th` :

```css
table th .cm-content.cm-lineWrapping,
table td .cm-content.cm-lineWrapping {
    padding-top: 0px !important;
    padding-bottom: 0px !important;
}
```

**Comment by luxuxl** [comment]
> Here's a quick fix:
> 
> ```css
> table td .cm-content.cm-lineWrapping {
>     padding-top: 0px !important;
>     padding-bottom: 0px !important;
> }
> ```
> 
> Create a file called `tw-table-fix.css` and add add it to the folder ".obsidian\snippets" inside your vault and activate the script under Settings > Appearance (scroll to the bottom of the settings page to do so)

not very exactly 

this one can fix both `thead` an `tbody`

```css
table tr .cm-content.cm-lineWrapping {
    padding-top: 0px !important;
    padding-bottom: 0px !important;
}
```
